services:
  # OpenScrapers Services
  crimson:
    build: .
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: .
    expose:
      - 8080
    ports:
      - 8080:8080
